server:
  port: 8080

spring:
  aop:
    auto: true #启动aop配置
  # mysql连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scaffold?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      pool-name: PrimaryDatabasePool
      minimum-idle: 5 # 最小连接数
      idle-timeout: 15000 # 单个连接的最长连接数 15s
      maximum-pool-size: 200 # 连接池最大数
      connection-timeout: 30000 # 单位ms 30s
      max-lifetime: 60000 # 超时自动时长60s
  # 多环境下配置使用不同的配置 可以设置为dev开发环境 test测试环境 prod正式环境
  #profiles:
  #active: dev
  redis:
    host: 192.168.25.139
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
  # 文件上传设置
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB

document:
  uploadPath: /data/txt


# mybatis 相关设置
mybatis:
  mapper-locations: classpath:mapper/mysql/*Mapper.xml,classpath*:/mapper/oracle/*Mapper.xml
